resources:
- ../../base

namespace: dev
namePrefix: dev-

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    env: dev
replacements:
- source:
    fieldPath: metadata.namespace
    kind: Service
    name: sample
    version: v1
  targets:
  - fieldPaths:
    - spec.rules.0.http.paths.0.path
    options:
      delimiter: /
      index: 1
    select:
      group: networking.k8s.io
      kind: Ingress
      name: sample
      namespace: default
      version: v1
