---
fullnameOverride: demo-app-1
image:
  registry: jenkins
  repository: jenkins
resources:
  requests:
    cpu: 30m
    memory: 512Mi
  limits:
    memory: 512Mi
ports:
  - name: http
    containerPort: 8080
    protocol: TCP

service:
  test: /login

readinessProbe: &httpProbe
  enabled: true
  httpGet:
    path: /login
    port: http
livenessProbe: *httpProbe
startupProbe:
  <: *httpProbe
  initialDelaySeconds: 60
