---
fullnameOverride: demo-jenkins
image:
  registry: docker.io
  repository: jenkins
resources:
  requests:
    cpu: 20m
    memory: 128Mi
  limits:
    memory: 128Mi
ports:
  - name: http
    containerPort: 8080
    protocol: TCP
