---
fullnameOverride: demo-jenkins
image:
  registry: jenkins
  repository: jenkins
resources:
  requests:
    cpu: 30m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 512Mi
ports:
  - name: http
    containerPort: 8080
    protocol: TCP

service:
  test: /login

readinessProbe: &httpProbe
  enabled: true
  httpGet:
    path: /login
    port: http
livenessProbe: *httpProbe
startupProbe:
  <: *httpProbe
  initialDelaySeconds: 60
# Security
containerSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  runAsUser: 1000
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - NET_RAW
      - ALL
