---
image:
  registry: docker.io
  repository: nginx
resources:
  requests:
    cpu: 20m
    memory: 128Mi
  limits:
    memory: 128Mi
ports:
  - name: http
    containerPort: 80
    protocol: TCP

readinessProbe: &httpProbe
  enabled: true
  httpGet:
    path: /
    port: http
livenessProbe: *httpProbe
