---
fullnameOverride: demo-app-1
image:
  registry: docker.io
  repository: nginx
resources:
  requests:
    cpu: 20m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 128Mi
ports:
  - name: http
    containerPort: 80
    protocol: TCP

readinessProbe: &httpProbe
  enabled: true
  httpGet:
    path: /
    port: http
livenessProbe: *httpProbe
# Security
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 101
  sysctls:
    - name: net.ipv4.ip_unprivileged_port_start
      value: "0"
containerSecurityContext:
  privileged: False
  capabilities:
    drop:
      - ALL
      - NET_RAW
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
extraVolumes:
  - name: cache
    emptyDir: {}
  - name: run
    emptyDir: {}
extraVolumeMounts:
  - name: cache
    mountPath: /var/cache/nginx
  - name: run
    mountPath: /var/run
