---
name: Release Library Charts
on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changes.outputs.all_changed_files_count }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: changes
        uses: tj-actions/changed-files@v45
        with:
          files: charts/demo-library/**

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: prepare
    if: needs.prepare.outputs.changed > 0
    env:
      CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@v4

      - name: Prepare for the release
        env:
          VERSION: ${{ github.ref_name }}
        working-directory: charts/demo-library
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          helm repo add helmet https://charts.companyinfo.dev
          sed -i "s#^version:.*#version: ${VERSION/v/}#g" Chart.yaml
          cat Chart.yaml

      - name: Commit file to branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Bumped up version [skip ci]"
          branch: main
          commit_user_name: Naviteq Automation
          commit_user_email: naviteq-automation@naviteq.io

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_existing: true

  dependencies-update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: azure/setup-helm@v4
      - uses: tj-actions/glob@v22
        id: glob
        with:
          files: |
            charts/**/Chart.yaml
            !charts/demo-library/Chart.yaml
      - name: Update dependencies if exists
        env:
          CHARTS: ${{ steps.glob.outputs.paths }}
        run: |
          set -e -x
          for chart in $CHARTS; do
            cd ${chart%/*}
            if grep "name: demo-library" Chart.yaml; then
              helm dependency update
            fi
            cd -
          done
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ github.token }}
          base: main
          branch: update/library-dependency
          delete-branch: true
          branch-suffix: timestamp
          commit-message: Updated library chart (${{ github.ref_name }})
          committer: ${{ github.actor }} <${{ github.actor}}@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          title: 'feature(auto): Updated dependency'
          labels: |
            report
            automated pr
          assignees: DovnarAlexander
          reviewers: DovnarAlexander
          add-paths: charts/
