---
name: Release Charts
on:
  push:
    # tags: ['v[0-9]+.[0-9]+.[0-9]+']
    # paths: ['charts/**']

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: changes
        uses: tj-actions/changed-files@v45
        with:
          files: charts/**

      - name: Output Data
        run: |
          echo "changes: ${{ steps.changed-files-specific.outputs.all_changed_files }}" 


#   release:
#     permissions:
#       contents: write
#     runs-on: ubuntu-latest
#     needs: prepare
#     env:
#       CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - uses: azure/setup-helm@v4

#       - name: Configure Git and Helm
#         run: |
#           git config user.name "$GITHUB_ACTOR"
#           git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
#           helm repo add helmet https://charts.companyinfo.dev
# rsions
#         working-directory: ${{ inputs.CHART_LOCATION }}
#         env:
#           VERSION: ${{ github.ref_name }}
#         run: |
#           sed -i "s#^version:.*#version: ${VERSION/v/}#g" Chart.yaml
#           cat Chart.yaml

#       - name: Run chart-releaser
#         uses: helm/chart-releaser-action@v1.6.0
#         with:
#           skip_existing: true
#           mark_as_latest: true
