---
name: Release Charts
on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.all_changed_files }}
      changed: ${{ steps.changes.outputs.all_changed_files_count }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: changes
        uses: tj-actions/changed-files@v45
        with:
          matrix: true
          dir_names: true
          files: charts/**
          files_ignore: charts/demo-library/**

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [prepare]
    if: needs.prepare.outputs.changed > 0
    strategy:
      matrix: 
        chart_folder: ${{ fromJSON(needs.prepare.outputs.changes) }}
      max-parallel: 1
      fail-fast: false
    env:
      CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@v4

      - name: Prepare for the release
        env:
          VERSION: ${{ github.ref_name }}
        working-directory: ${{ matrix.chart_folder }}
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          helm repo add demo https://alex-dovnar.in/devopsdays-kz-2024
          sed -i "s#^version:.*#version: ${VERSION/v/}#g" Chart.yaml
          cat Chart.yaml

      - name: Commit file to branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Bumped up version [skip ci]"
          branch: main
          author: ${{ github.actor }}
          commit_user_email: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_existing: true
          mark_as_latest: true
