---
name: Release Charts
on:
  push:
    branches: ['main']
    paths:
      - 'charts/**'
      - '!charts/demo-library/**'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: changes
        uses: tj-actions/changed-files@v45
        with:
          matrix: true
          dir_names: true
          dir_names_max_depth: 1
          files: '**'
          path: charts

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [prepare]
    strategy:
      matrix: 
        chart: ${{ fromJSON(needs.prepare.outputs.changes) }}
      max-parallel: 1
      fail-fast: false
    env:
      CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/release
        with:
          chart: ${{ matrix.chart }}
