---
name: Release Library Chart
on:
  push:
    branches: ['main']
    paths:
      - 'charts/demo-library/**'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/release
        with:
          chart: demo-library

  dependencies-update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: azure/setup-helm@v4
      - uses: tj-actions/glob@v22
        id: glob
        with:
          files: |
            charts/**/Chart.yaml
            !charts/demo-library/Chart.yaml
      - name: Update dependencies if exists
        env:
          CHARTS: ${{ steps.glob.outputs.paths }}
        run: |
          set -e -x
          for chart in $CHARTS; do
            cd ${chart%/*}
            if grep "name: demo-library" Chart.yaml; then
              helm dependency update
            fi
            cd -
          done
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ github.token }}
          base: main
          branch: update/library-dependency
          delete-branch: true
          branch-suffix: timestamp
          commit-message: Updated library chart (${{ github.ref_name }})
          committer: ${{ github.actor }} <${{ github.actor}}@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          title: 'feature(auto): Updated dependency'
          labels: |
            report
            automated pr
          assignees: DovnarAlexander
          reviewers: DovnarAlexander
          add-paths: charts/
