---
name: Test application charts
on:
  pull_request:
    branches: ['main']
    ignore-paths: ['charts/demo-library/**']
    paths:
      - 'charts/**'
      - '.github/workflows/test-library.yaml'
  push:
    branches: ['main']
    ignore-paths: ['charts/demo-library/**']
    paths:
      - 'charts/**'
      - '.github/workflows/test-library.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ct
