---
name: Test application charts
on:
  pull_request:
    branches: ['main']
    paths:
      - 'charts/**'
      - '!charts/demo-library/**'
      - '.github/workflows/test-library.yaml'
  push:
    branches: ['main']
    paths:
      - 'charts/**'
      - '!charts/demo-library/**'
      - '.github/workflows/test-library.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ct
